:hivemq-plugin-docs-link: http://www.hivemq.com/docs/plugins/latest/
:hivemq-blog-tools: http://www.hivemq.com/overview-of-mqtt-client-tools/

= MQTT Message Log Plugin

== Description

The MQTT Message Log is a very useful HiveMQ Plugin for debugging and development purposes. It provides the possibility to follow up on any clients communicating with the broker on the terminal.

*The plugin logs the following events:*

* A client connects to HiveMQ
* A client sends a publish message
* A client subscribes to a topic
* A client unsubscribes from a topic
* A client disconnects from HiveMQ
* HiveMQ send a message to a client


== How to use the plugin

. Copy the jar file to your +<HIVEMQ_HOME>/plugins+ folder
. Run HiveMQ
. Connect with a {hivemq-blog-tools}[MQTT client] of your choice and publish something.
. You should see logged events in your terminal where you started HiveMQ

== Configuration

It is possible to opt out of specific log event types by adding a
*mqttMessageLog.properties* files to your +<HIVEMQ_HOME>/conf+  folder.

This properties file could have the following entries:

* client-connect=false|true
* client-disconnect=false|true
* publish-received=false|true
* publish-send=false|true
* subscribe-received=false|true
* unsubscribe-received=false|true

Missing entries defaults to true.

= Contributing

If you want to contribute to HiveMQ Message Log Plugin, see the link:CONTRIBUTING.md[contribution guidelines].

= License

HiveMQ Message Log Plugin is licensed under the `APACHE LICENSE, VERSION 2.0`. A copy of the license can be found link:LICENSE.txt[here].
